spring:
  data:
    mongodb:
      uri: "mongodb://${USERNAME}:${PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/ctr?authSource=admin&serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=2000"
#      host: ${MONGO_HOST
#      port: ${MONGO_PORT}
#      username: ${USERNAME}
#      password: ${PASSWORD}
#      database: ctr
#      authenticationDatabase: admin

management:
  endpoints:
    web:
      base-path: /ctr
      exposure:
        include:
          - beans
          - prometheus
          - health
server:
  error:
    whitelabel:
      enabled: false





