spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      username: ${USERNAME}
      password: ${PASSWORD}
      database: ctr
      authenticationDatabase: admin

management:
  endpoints:
    web:
      base-path: /ctr
      exposure:
        include:
          - beans
          - prometheus
          - health





