global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'service'
    scrape_interval: 10s
    metrics_path: '/ctr/prometheus'
    static_configs:
      - targets: [ 'service:8080' ]